name: 'Terraform Setup and Validate'

on:
  workflow_call:
    inputs:
      terraform-version:
        required: false
        type: string
      terraform-path:
        required: false
        type: string

permissions:
  contents: read
  packages: read

jobs:
  terraform-setup:
    container: 
      image: ghcr.io/ukhsa-internal/devops-terraform-ci:latest
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Check and set Terraform version'
      run: |
        if [[ ! "${{ inputs.terraform-version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Error: terraform-version input must be in the format v0-9.0-9.0-9 or be blank"
          exit 1
        else
          tfenv use ${{ inputs.terraform-version }}
        fi
      if: ${{ inputs.terraform-version != '' }}

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Validate'
      run: terraform validate
