name: "[Test] Lint and Deploy Terraform stacks"

on:
  pull_request:
    # branches:
    #   - main
    # paths:
    #   - ./.github/workflows/terraform-ci.yml
    #   - ./.github/workflows/_test_terraform-ci.yml

jobs:
  test_workflow:
    name: Test using devops-terraform-example-project@main
    uses: ./.github/workflows/terraform-plan-apply.yml
    with:
      repo: UKHSA-Internal/devops-terraform-example-project
      ref: "main"
    secrets:
      SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}