name: "[Analysis] Run post deployment QA checks"
on:
  workflow_call:
    inputs:
      environment_name:
        required: false
        default: dev
        type: string
      aws_region:
        required: false
        default: eu-west-2
        type: string
      runner_label:
        required: false
        type: string
        default: "ubuntu-latest"
        description: "Specifies a targetted runner for the job. Use \"self-hosted\" if you've configured a self hosted runner, otherwise leave as the default."
      zap_api_scan:
        required: false
        type: boolean
        default: false
      zap_endpoint_scan:
        required: false
        type: boolean
        default: false
      prowler_scan:
        required: false
        type: boolean
        default: true
      create_threat_model:
        required: false
        type: boolean
        default: true

    secrets:
      AWS_ROLE_NAME:
        required: false
      AWS_ACCOUNT_ID:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      AZURE_SUBSCRIPTION_ID:
        required: false
      AZURE_TENANT_ID:
        required: false
      AZURE_CLIENT_ID:
        required: false
      AZURE_RESOURCE_GROUP_NAME:
        required: false
        
jobs:
  cloud-configuration-scan:
    name: Run scans to check for cloud misconfigurations, DAST and threat model.
    runs-on: ${{ inputs.runner_label }}
    steps:
      - uses: actions/checkout@v4
      - name: DAST - ZAP API workflow/action.
        if: ${{ inputs.zap_api_scan == true }}
        run: |
          echo "#TODO; Run ZAP API scan."

      - name: DAST - ZAP baseline scan workflow/action.
        if: ${{ inputs.zap_endpoint_scan == true }}
        run: |
          echo "#TODO; Run ZAP baseline scan against endpoints."

      - name: CSPM - Run Prowler workflow/action.
        if: ${{ inputs.prowler_scan == true }}
        run: |
          echo "#TODO; Run Prowler."

      - name: Create threat model using Irius Risk workflow/action.
        if: ${{ inputs.create_threat_model == true }}
        run: |
          echo "#TODO; Create master plan and run Irius Risk."