name: 'Terraform CI'

on:
  workflow_call:
    inputs:
      terraform-version:
        required: false
        type: string
      terraform-path:
        required: false
        type: string

permissions:
  contents: write
  packages: read

jobs:
  terraform-formatting:
    container: 
      image: ghcr.io/ukhsa-internal/devops-terraform-ci:latest
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref_name }} 

    - name: 'Setup Terraform'
      uses: ./.github/actions/setup-terraform.yml

    - name: 'Terraform Format'
      run: terraform fmt

    - name: 'Terraform Lint'
      run: tflint --recursive --config "$(pwd)/.tflint.hcl"

    - name: 'Terraform Docs'
      run: terraform-docs markdown table --output-file README.md --output-mode inject "$(pwd)"

    - name: Check for changes
      id: git-status
      run: |
        git config --global --add safe.directory "$(pwd)"
        if [ -n "$(git status --porcelain)" ]; then
          echo "dirty=true" >> "$GITHUB_OUTPUT"
        else
          echo "dirty=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Commit and push changes
      if: steps.git-status.outputs.dirty == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "[automated] Terraform formatting and documentation updates"
        git push

  terraform-checks:
    container: 
      image: ghcr.io/ukhsa-internal/devops-terraform-ci:latest
    runs-on: ubuntu-latest
    needs: [ terraform-formatting ] 
    
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4

    - name: 'Setup Terraform'
      uses: ./.github/workflows/setup-terraform.yml

    - name: 'Checkov Scan'
      run: checkov -d . --quiet --compact

  terraform-run:
    container: 
      image: ghcr.io/ukhsa-internal/devops-terraform-ci:latest
    runs-on: ubuntu-latest
    needs: [terraform-formatting, terraform-checks]
    
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4

    - name: 'Setup Terraform'
      uses: ./.github/workflows/setup-terraform.yml

    - name: 'Terraform Plan'
      run: terraform plan -no-color -input=false
